/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new player */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Registration successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["RegisterResponseData"];
                            /** @example Registration successful. */
                            message?: string;
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and obtain tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["LoginResponseData"];
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Tokens refreshed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["RefreshResponseData"];
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and revoke refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Logged out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: Record<string, never> | null;
                            /** @example Logged out successfully. */
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/player/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current player profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Player profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PlayerMe"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/player/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update player profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nickname?: string;
                        language?: string;
                    };
                };
            };
            responses: {
                /** @description Profile updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PlayerProfileUpdate"];
                            /** @example Profile updated. */
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/wallet/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get wallet balance */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Wallet balance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["WalletBalance"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List wallet transactions */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated transactions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["WalletTransaction"][];
                                pagination: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active payment methods */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment methods */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PaymentMethod"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deposit requests */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated deposits */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PaginatedDeposits"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create deposit request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        payment_method_id: number;
                        /**
                         * @description Decimal amount with up to 4 decimal places
                         * @example 100.0000
                         */
                        amount: string;
                    };
                };
            };
            responses: {
                /** @description Deposit created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["DepositCreated"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List withdrawal requests */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated withdrawals */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PaginatedWithdrawals"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create withdrawal request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        payment_method_id: number;
                        /** @example 50.0000 */
                        amount: string;
                        destination: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Withdrawal created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["WithdrawalCreated"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bonus/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available bonus policies */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Available bonuses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["BonusPolicy"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bonus/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active player bonuses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active bonuses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["ActiveBonus"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bonus/{policyId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim a bonus policy */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    policyId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bonus claimed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["BonusClaimed"];
                            /** @example Bonus claimed. */
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List internal messages */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["InternalMessage"][];
                                pagination: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List game vendors */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Game vendors */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["GameVendor"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List game types */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Game types */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["GameType"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/collections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game collection by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Game collection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["GameCollection"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List games */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by vendor ID */
                    vendor?: number;
                    /** @description Filter by type slug (e.g. slot) */
                    type?: string;
                    /** @description Filter by collection slug */
                    collection?: string;
                    search?: string;
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated games */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["Game"][];
                                pagination: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get game detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Game detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Game"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch a game session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Launch URL and session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["GameLaunchResult"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
                /** @description Provider launch error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: unknown;
            message: string | null;
        };
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            error: {
                /** @enum {string} */
                code: "VALIDATION_ERROR" | "NOT_FOUND" | "LAUNCH_ERROR" | "UNAUTHORIZED" | "FORBIDDEN";
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        Pagination: {
            current_page: number;
            per_page: number;
            total: number;
            last_page: number;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            password_confirmation: string;
            nickname: string;
            /** @example KR */
            country: string;
            /** @example KRW */
            currency: string;
            affiliate_code?: string | null;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            device_fingerprint?: string | null;
            device_name?: string | null;
        };
        UserSummary: {
            id: number;
            /** Format: email */
            email: string;
        };
        RegisterResponseData: {
            user: components["schemas"]["UserSummary"];
            access_token: string;
            /** @description Access token TTL in seconds */
            expires_in: number;
        };
        LoginResponseData: {
            access_token: string;
            expires_in: number;
            refresh_token: string;
            user: components["schemas"]["UserSummary"];
        };
        RefreshResponseData: {
            access_token: string;
            refresh_token: string;
        };
        PlayerMe: {
            id?: number | null;
            user_id?: number | null;
            /** Format: email */
            email?: string | null;
            nickname?: string | null;
            country?: string | null;
            currency?: string | null;
            status?: string | null;
            kyc_status?: string | null;
        };
        PlayerProfileUpdate: {
            id?: number;
            nickname?: string | null;
            language?: string | null;
        };
        WalletBalance: {
            wallet_id: number;
            player_id: number;
            currency: string;
            /** @example 1250.0000 */
            balance: string;
            status: string;
        };
        WalletTransaction: {
            id: number;
            type: string;
            amount: string;
            status: string;
            description?: string | null;
            /** Format: date-time */
            created_at?: string | null;
        };
        PaymentMethod: {
            id: number;
            type: string;
            name: string;
            min_amount: string;
            max_amount?: string | null;
        };
        DepositCreated: {
            deposit_id: number;
            status: string;
            amount: string;
            payment_info: {
                [key: string]: unknown;
            };
        };
        WithdrawalCreated: {
            withdrawal_id: number;
            status: string;
            amount: string;
        };
        DepositItem: {
            id?: number;
            amount?: string;
            currency?: string;
            status?: string;
            payment_method?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            confirmed_at?: string | null;
        };
        WithdrawalItem: {
            id?: number;
            amount?: string;
            currency?: string;
            status?: string;
            payment_method?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            processed_at?: string | null;
        };
        PaginatedDeposits: {
            items: components["schemas"]["DepositItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        PaginatedWithdrawals: {
            items: components["schemas"]["WithdrawalItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        BonusPolicy: {
            policy_id: number;
            name: string;
            type: string;
            amount_type: string;
            amount_value: string;
            wagering_multiplier: number;
        };
        ActiveBonus: {
            id?: number;
            policy_name?: string | null;
            amount?: string;
            status?: string;
            wagering?: {
                required?: string;
                wagered?: string;
            } | null;
        };
        BonusClaimed: {
            bonus_id: number;
            amount: string;
            status: string;
        };
        InternalMessage: {
            id?: number;
            subject?: string;
            body?: string;
            is_read?: boolean;
            /** Format: date-time */
            created_at?: string | null;
        };
        GameVendor: {
            id: number;
            slug: string;
            name: string;
            logo_url?: string | null;
            game_count: number;
        };
        GameType: {
            id: number;
            slug: string;
            name: string;
            icon?: string | null;
            game_count: number;
        };
        GameVendorRef: {
            id?: number;
            slug?: string;
            name?: string;
        };
        GameTypeRef: {
            id?: number;
            slug?: string;
            name?: string;
        };
        Game: {
            id: number;
            name: string;
            name_ko?: string | null;
            thumbnail?: string | null;
            game_code: string;
            symbol?: string | null;
            vendor?: components["schemas"]["GameVendorRef"];
            type?: components["schemas"]["GameTypeRef"];
        };
        GameCollection: {
            slug: string;
            name: string;
            games: components["schemas"]["Game"][];
        };
        GameLaunchResult: {
            /** Format: uri */
            launch_url: string;
            session_id: number;
            session_token: string;
            /** Format: date-time */
            expires_at?: string | null;
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        PerPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
