/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supported registration currencies and countries */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Registration options */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["RegisterOptionsData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player session policy for client-side idle logout */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session policy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["SessionPolicyData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new player */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Registration successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["RegisterResponseData"];
                            /** @example Registration successful. */
                            message?: string;
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and obtain tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["LoginResponseData"];
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Tokens refreshed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["RefreshResponseData"];
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and revoke refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Logged out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: Record<string, never> | null;
                            /** @example Logged out successfully. */
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-recovery/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password recovery verification code
         * @description Sends a numeric verification code by email or SMS when an active player account exists.
         *     Provide exactly one of `email` or `phone` (E.164). Always returns success to avoid enumeration.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordRecoveryRequestBody"];
                };
            };
            responses: {
                /** @description Request accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: Record<string, never> | null;
                            /** @example If an account exists for this email, a verification code has been sent. */
                            message?: string;
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-recovery/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password using email or phone verification code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordRecoveryResetBody"];
                };
            };
            responses: {
                /** @description Password reset successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: Record<string, never> | null;
                            /** @example Password has been reset successfully. */
                            message?: string;
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
                429: components["responses"]["TooManyRequests"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/player/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current player profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Player profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PlayerMe"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/player/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update player profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nickname?: string;
                        language?: string;
                    };
                };
            };
            responses: {
                /** @description Profile updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PlayerProfileUpdate"];
                            /** @example Profile updated. */
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/player/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change player password */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePlayerPasswordBody"];
                };
            };
            responses: {
                /** @description Password updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: Record<string, never> | null;
                            /** @example Password updated successfully. */
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get wallet balance */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Wallet balance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["WalletBalance"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List wallet transactions */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                    /** @description Comma-separated transaction types (deposit, withdraw, bet, win, rollback, bonus) */
                    type?: string;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated transactions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["WalletTransaction"][];
                                pagination: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List countries available for deposit and withdrawal */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment countries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PaymentCountryList"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/deposit-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deposit payment options for a country */
        get: {
            parameters: {
                query: {
                    country: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deposit options */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PaymentOptionList"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/withdraw-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List withdrawal payment options for a country */
        get: {
            parameters: {
                query: {
                    country: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Withdrawal options */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PaymentOptionList"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/deposits/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estimate wallet credit for a deposit amount (FX preview) */
        get: {
            parameters: {
                query: {
                    option_key: string;
                    amount: string;
                    country: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deposit credit estimate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["DepositQuote"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deposit requests */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated deposits */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PaginatedDeposits"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create deposit request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Selected payment option key from deposit-options response
                         * @example local:4:ID:QRIS
                         */
                        option_key: string;
                        /**
                         * @description Decimal amount with up to 4 decimal places
                         * @example 100.0000
                         */
                        amount: string;
                        /**
                         * @description ISO 3166-1 alpha-2 country code
                         * @example ID
                         */
                        country: string;
                    };
                };
            };
            responses: {
                /** @description Deposit created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["DepositCreated"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List withdrawal requests */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated withdrawals */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PaginatedWithdrawals"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create withdrawal request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Selected payment option key from withdraw-options response
                         * @example crypto:2:btc
                         */
                        option_key: string;
                        /** @example 50.0000 */
                        amount: string;
                        /** @example US */
                        country: string;
                        /** @description Destination fields (address, account, network, etc.) based on option destination_fields */
                        destination: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Withdrawal created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["WithdrawalCreated"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bonus/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available bonus policies */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Available bonuses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["BonusPolicy"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bonus/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active player bonuses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active bonuses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["ActiveBonus"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bonus/{policyId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim a bonus policy */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    policyId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bonus claimed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["BonusClaimed"];
                            /** @example Bonus claimed. */
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/affiliate/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get affiliate profile and referral link */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Affiliate profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AffiliateMe"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/affiliate/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get affiliate dashboard statistics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Affiliate stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AffiliateStats"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/affiliate/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List referred players */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated referred players */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AffiliatePlayerList"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/affiliate/commissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List commission history */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated commissions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AffiliateCommissionList"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/affiliate/sub-affiliates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sub-affiliates (top-level affiliates only) */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated sub-affiliates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AffiliateSubAffiliateList"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Create a sub-affiliate */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSubAffiliateRequest"];
                };
            };
            responses: {
                /** @description Sub-affiliate created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AffiliateSubAffiliate"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/affiliate/sub-affiliates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a sub-affiliate */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSubAffiliateRequest"];
                };
            };
            responses: {
                /** @description Sub-affiliate updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AffiliateSubAffiliate"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/affiliate/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change password with current password */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePlayerPasswordBody"];
                };
            };
            responses: {
                /** @description Password updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List internal messages */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["InternalMessage"][];
                                pagination: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List game vendors */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Game vendors */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["GameVendor"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List game types */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Game types */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["GameType"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/collections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game collection by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Game collection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["GameCollection"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List games */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by vendor ID */
                    vendor?: number;
                    /** @description Filter by type slug (e.g. slot) */
                    type?: string;
                    /** @description Filter by collection slug */
                    collection?: string;
                    search?: string;
                    per_page?: components["parameters"]["PerPage"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated games */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["Game"][];
                                pagination: components["schemas"]["Pagination"];
                            };
                        };
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List player bet history (game rounds) */
        get: {
            parameters: {
                query?: {
                    per_page?: components["parameters"]["PerPage"];
                    game_id?: number;
                    status?: "bet" | "settled" | "cancelled";
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated bet history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PaginatedBetHistory"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get game detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Game detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Game"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch a game session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Launch URL and session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["GameLaunchResult"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
                /** @description Provider launch error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: unknown;
            message: string | null;
        };
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            error: {
                /** @enum {string} */
                code: "VALIDATION_ERROR" | "NOT_FOUND" | "LAUNCH_ERROR" | "UNAUTHORIZED" | "FORBIDDEN";
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        Pagination: {
            current_page: number;
            per_page: number;
            total: number;
            last_page: number;
        };
        RegisterOptionsData: {
            currencies: components["schemas"]["RegistrationCurrency"][];
            countries: components["schemas"]["RegistrationCountry"][];
        };
        SessionPolicyData: {
            /** @description Minutes of inactivity before automatic logout. 0 disables idle logout. */
            idle_timeout_minutes: number;
        };
        RegistrationCurrency: {
            /** @example USD */
            code: string;
            /** @example US Dollar */
            name: string;
        };
        RegistrationCountry: {
            /** @example US */
            code: string;
            /** @example United States */
            name: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            password_confirmation: string;
            nickname: string;
            /**
             * @description Phone number in E.164 format (country dial code + digits, no spaces)
             * @example +12025550123
             */
            phone: string;
            /**
             * @description ISO 3166-1 alpha-2 code from GET /auth/register-options
             * @example US
             */
            country: string;
            /**
             * @description ISO 4217 code from GET /auth/register-options
             * @example USD
             */
            currency: string;
            affiliate_code?: string | null;
        };
        LoginRequest: {
            /** @description Email address (use with password for email login) */
            email?: string;
            /** @description Username (use with password for username login) */
            username?: string;
            /** @description Phone number in E.164 format (use with password for phone login) */
            phone?: string;
            password: string;
            device_fingerprint?: string | null;
            device_name?: string | null;
        };
        /** @description Exactly one of email or phone is required. */
        PasswordRecoveryRequestBody: {
            /**
             * Format: email
             * @example player@example.com
             */
            email?: string;
            /**
             * @description Phone number in E.164 format
             * @example +12025550123
             */
            phone?: string;
        };
        /** @description Exactly one of email or phone is required (same channel used for the code request). */
        PasswordRecoveryResetBody: {
            /**
             * Format: email
             * @example player@example.com
             */
            email?: string;
            /** @example +12025550123 */
            phone?: string;
            /**
             * @description Six-digit verification code sent by email or SMS
             * @example 123456
             */
            code: string;
            password: string;
            password_confirmation: string;
        };
        UserSummary: {
            id: number;
            /** Format: email */
            email: string;
            /**
             * @description User role (player, affiliate, admin, operator)
             * @example player
             */
            role?: string;
        };
        RegisterResponseData: {
            user: components["schemas"]["UserSummary"];
            access_token: string;
            /** @description Access token TTL in seconds */
            expires_in: number;
        };
        LoginResponseData: {
            access_token: string;
            expires_in: number;
            refresh_token: string;
            user: components["schemas"]["UserSummary"];
        };
        RefreshResponseData: {
            access_token: string;
            refresh_token: string;
        };
        PlayerMe: {
            id?: number | null;
            user_id?: number | null;
            /** Format: email */
            email?: string | null;
            nickname?: string | null;
            /**
             * @description Phone number in E.164 format
             * @example +12025550123
             */
            phone?: string | null;
            /**
             * @description ISO 3166-1 alpha-2 country code
             * @example SG
             */
            country?: string | null;
            /**
             * @description Human-readable country name resolved from platform config
             * @example Singapore
             */
            country_name?: string | null;
            currency?: string | null;
            /** @example en */
            language?: string | null;
            /**
             * @description Player account status
             * @example active
             */
            status?: string | null;
            /**
             * @description KYC verification status
             * @example pending
             */
            kyc_status?: string | null;
        };
        PlayerProfileUpdate: components["schemas"]["PlayerMe"];
        ChangePlayerPasswordBody: {
            current_password: string;
            password: string;
            password_confirmation: string;
        };
        WalletBalance: {
            wallet_id: number;
            player_id: number;
            currency: string;
            /** @example 1250.0000 */
            balance: string;
            status: string;
        };
        WalletBalanceEvent: components["schemas"]["WalletBalance"] & {
            ledger_id?: number | null;
            /** @example payment.deposit */
            event_type?: string;
        };
        WalletTransaction: {
            id: number;
            type: string;
            amount: string;
            balance_after?: string | null;
            status: string;
            description?: string | null;
            reference_type?: string | null;
            reference_id?: string | null;
            /** Format: date-time */
            created_at?: string | null;
        };
        BetHistoryGame: {
            id?: number | null;
            name?: string;
            provider?: string | null;
        };
        BetHistoryItem: {
            id: number;
            round_id: string;
            game?: components["schemas"]["BetHistoryGame"];
            bet_amount: string;
            win_amount: string;
            net_amount: string;
            status: string;
            currency: string;
            /** Format: date-time */
            played_at?: string | null;
        };
        PaginatedBetHistory: {
            items: components["schemas"]["BetHistoryItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        PaymentCountry: {
            /** @example ID */
            code: string;
            /** @example Indonesia */
            name: string;
        };
        PaymentCountryList: {
            countries: components["schemas"]["PaymentCountry"][];
            /** @example ID */
            default_country?: string | null;
        };
        PaymentDestinationField: {
            /** @example address */
            name: string;
            /** @example Wallet address */
            label: string;
            required: boolean;
        };
        PaymentOption: {
            /** @example local:4:PH:GCASH */
            key: string;
            payment_method_id: number;
            /** @enum {string} */
            kind: "local" | "crypto" | "manual";
            /** @example smilepayz */
            provider?: string | null;
            /** @example GCash */
            label: string;
            description?: string | null;
            logo_url?: string | null;
            /** @example gcash */
            logo_key?: string | null;
            /** @example PHP */
            payment_currency: string;
            /**
             * @description Minimum deposit amount in payment_currency. For local deposit options this value is converted from the player's wallet currency, normalized for display, and expressed in the regional payment currency (e.g. IDR, PHP).
             * @example 10000.0000
             */
            min_amount: string;
            /**
             * @description Maximum deposit amount in payment_currency, or null when no limit applies. For local deposit options this value is converted from the player's wallet currency, normalized for display, and expressed in the regional payment currency.
             * @example 150000000.0000
             */
            max_amount?: string | null;
            /** @example PH */
            local_country?: string | null;
            /** @example GCASH */
            local_payment_method?: string | null;
            /** @example btc */
            pay_currency?: string | null;
            destination_fields: components["schemas"]["PaymentDestinationField"][];
        };
        PaymentOptionList: {
            country: components["schemas"]["PaymentCountry"];
            items: components["schemas"]["PaymentOption"][];
        };
        DepositQuote: {
            payment_amount: string;
            payment_currency: string;
            credited_amount: string;
            wallet_currency: string;
            exchange_rate: string;
            /** Format: date-time */
            exchange_rate_at?: string;
            rate_display?: string;
            /** @description True for preview; final credit is determined at payment confirmation */
            is_estimate: boolean;
        };
        DepositCreated: {
            deposit_id: number;
            status: string;
            amount: string;
            currency?: string;
            estimated_credit?: components["schemas"]["DepositQuote"] | null;
            payment_info: {
                [key: string]: unknown;
            };
        };
        WithdrawalCreated: {
            withdrawal_id: number;
            status: string;
            amount: string;
        };
        DepositItem: {
            id?: number;
            amount?: string;
            /** @description Actual amount received from the payment provider (payment currency) */
            received_amount?: string | null;
            currency?: string;
            /** @description Wallet points credited after confirmation */
            credited_amount?: string | null;
            credited_currency?: string | null;
            status?: string;
            payment_method?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            confirmed_at?: string | null;
        };
        WithdrawalItem: {
            id?: number;
            amount?: string;
            currency?: string;
            status?: string;
            payment_method?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            processed_at?: string | null;
        };
        PaginatedDeposits: {
            items: components["schemas"]["DepositItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        PaginatedWithdrawals: {
            items: components["schemas"]["WithdrawalItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        BonusPolicy: {
            policy_id: number;
            name: string;
            type: string;
            amount_type: string;
            amount_value: string;
            wagering_multiplier: number;
            claimable: boolean;
            /** @enum {string|null} */
            claim_blocked_reason?: "deposit_required" | "already_claimed" | "provider_not_supported" | null;
            spin_count?: number | null;
            provider_slug?: string | null;
            provider_name?: string | null;
        };
        ActiveBonus: {
            id?: number;
            policy_name?: string | null;
            type?: string | null;
            amount?: string;
            status?: string;
            wagering?: {
                required?: string;
                wagered?: string;
            } | null;
            spin_count?: number | null;
            provider_slug?: string | null;
            provider_bonus_id?: number | null;
        };
        BonusClaimed: {
            bonus_id: number;
            amount: string;
            status: string;
            spin_count?: number | null;
            provider_bonus_id?: number | null;
        };
        InternalMessage: {
            id?: number;
            subject?: string;
            body?: string;
            is_read?: boolean;
            /** Format: date-time */
            created_at?: string | null;
        };
        GameVendor: {
            id: number;
            slug: string;
            name: string;
            logo_url?: string | null;
            sort_order: number;
            game_count: number;
        };
        GameType: {
            id: number;
            slug: string;
            name: string;
            icon?: string | null;
            game_count: number;
        };
        GameVendorRef: {
            id?: number;
            slug?: string;
            name?: string;
        };
        GameTypeRef: {
            id?: number;
            slug?: string;
            name?: string;
        };
        Game: {
            id: number;
            name: string;
            name_ko?: string | null;
            thumbnail?: string | null;
            game_code: string;
            symbol?: string | null;
            vendor?: components["schemas"]["GameVendorRef"];
            type?: components["schemas"]["GameTypeRef"];
        };
        GameCollection: {
            slug: string;
            name: string;
            games: components["schemas"]["Game"][];
        };
        GameLaunchResult: {
            /** Format: uri */
            launch_url: string;
            session_id: number;
            session_token: string;
            /** Format: date-time */
            expires_at?: string | null;
        };
        AffiliateMe: {
            code: string;
            /** @enum {string} */
            commission_model: "cpa" | "revshare" | "hybrid";
            commission_rate: string;
            cpa_amount?: string | null;
            /** @enum {string} */
            status: "active" | "inactive";
            /** @example ?ref=AFF001 */
            referral_link: string;
            is_sub_affiliate: boolean;
            can_manage_sub_affiliates: boolean;
            parent_code?: string | null;
            /** Format: email */
            email?: string | null;
            email_verified?: boolean;
        };
        AffiliateStats: {
            referred_players_count: number;
            commissions_count: number;
            total_commission: string;
            pending_commission: string;
            sub_affiliates_count?: number;
            downline_players_count?: number;
            override_commission?: string;
            pending_override_commission?: string;
        };
        AffiliateReferredPlayer: {
            player_id: number;
            nickname?: string | null;
            /** Format: date-time */
            registered_at: string;
        };
        AffiliatePlayerList: {
            items: components["schemas"]["AffiliateReferredPlayer"][];
            pagination: components["schemas"]["Pagination"];
        };
        AffiliateCommission: {
            id: number;
            player_id: number;
            /** @enum {string} */
            type: "cpa" | "revshare" | "override";
            amount: string;
            reference_type: string;
            reference_id: string;
            /** @enum {string} */
            status: "pending" | "paid";
            /** Format: date-time */
            created_at?: string | null;
        };
        AffiliateCommissionList: {
            items: components["schemas"]["AffiliateCommission"][];
            pagination: components["schemas"]["Pagination"];
        };
        AffiliateSubAffiliate: {
            id: number;
            code: string;
            /** @enum {string} */
            commission_model: "cpa" | "revshare" | "hybrid";
            commission_rate: string;
            cpa_amount?: string | null;
            /** @enum {string} */
            status: "active" | "inactive";
            referred_players_count: number;
            /** Format: date-time */
            created_at?: string | null;
        };
        AffiliateSubAffiliateList: {
            items: components["schemas"]["AffiliateSubAffiliate"][];
            pagination: components["schemas"]["Pagination"];
        };
        CreateSubAffiliateRequest: {
            code: string;
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            commission_model: "cpa" | "revshare" | "hybrid";
            commission_rate?: number;
            cpa_amount?: number;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
        UpdateSubAffiliateRequest: {
            /** @enum {string} */
            commission_model?: "cpa" | "revshare" | "hybrid";
            commission_rate?: number;
            cpa_amount?: number | null;
            /** @enum {string} */
            status?: "active" | "inactive";
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Too many requests */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        PerPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
